name: Code quality CI

on:
  push:
    branches: ["feature/**", "dev", "main"]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  lint:
    name: Python Code Quality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Run Ruff checks
      run: |
        uvx ruff check .
        uvx ruff format --check .