name: Security Scan

on:
  push:
    branches: ["feature/**", "dev", "main"]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  gitleaks:
    name: Detect Secrets
    runs-on: ubuntu-22.04
    permissions:            # Least privilege
      contents: read          # For checkout
      pull-requests: read     # For PR events
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
